# Shows the "Sponsor" button on the repo page.
custom:
  - "https://www.paypal.com/donate/?business=stinger2404%40gmail.com&currency_code=USD"
  - "https://github.com/Tendai2404/monatomic-music-player#-support-the-project"
